[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"

# Environment variables for cross-compilation
[env]
CC_x86_64_unknown_linux_musl = "x86_64-linux-musl-gcc"
CC_x86_64_pc_windows_gnu = "x86_64-w64-mingw32-gcc" 