name: Release and Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: '1.1.2'

permissions:
  contents: write
  pull-requests: read
  packages: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: aws-assume-role
            asset_name: aws-assume-role-linux-x86_64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: aws-assume-role.exe
            asset_name: aws-assume-role.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: aws-assume-role
            asset_name: aws-assume-role-macos-x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: aws-assume-role
            asset_name: aws-assume-role-macos-arm64

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
    
    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Cache cargo index
      uses: actions/cache@v3
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Cache cargo build
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Build
      run: cargo build --release --target ${{ matrix.target }}
    
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
        overwrite: true
        make_latest: true
        release_name: "AWS Assume Role CLI ${{ github.ref_name }}"
        body: |
          # 🎉 AWS Assume Role CLI ${{ github.ref_name }} - Release
          
          A simple command-line tool to easily switch between AWS IAM roles across different accounts, designed for SSO users.
          
          ## 📦 Installation
          
          Download the appropriate binary for your platform from the assets below, or use package managers:
          
          ```bash
          # Homebrew (macOS/Linux)
          brew tap holdennguyen/tap
          brew install aws-assume-role
          
          # APT (Debian/Ubuntu)
          sudo add-apt-repository ppa:holdennguyen/aws-assume-role
          sudo apt update
          sudo apt install aws-assume-role
          
          # DNF/YUM (Fedora/CentOS/RHEL)
          sudo dnf copr enable holdennguyen/aws-assume-role
          sudo dnf install aws-assume-role
          
          # Cargo (Rust)
          cargo install aws-assume-role
          ```
          
          ## 🚀 Quick Start
          
          ```bash
          # Configure a role
          awsr configure --name dev --role-arn arn:aws:iam::123456789012:role/DevRole --account-id 123456789012
          
          # Assume the role
          awsr assume dev
          ```

  publish-cargo:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Publish to crates.io
      run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

  create-multi-shell-package:
    name: Create multi-shell distribution package
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all binaries
      run: |
        mkdir -p temp-binaries
        curl -L -o temp-binaries/aws-assume-role-macos-x86_64 \
          "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/aws-assume-role-macos-x86_64"
        curl -L -o temp-binaries/aws-assume-role-macos-arm64 \
          "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/aws-assume-role-macos-arm64"
        curl -L -o temp-binaries/aws-assume-role-linux-x86_64 \
          "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/aws-assume-role-linux-x86_64"
        curl -L -o temp-binaries/aws-assume-role.exe \
          "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/aws-assume-role.exe"
    
    - name: Prepare binaries for distribution
      run: |
        # Clean old distribution files
        rm -rf releases/multi-shell/dist/
        
        # Copy binaries (skip universal macOS binary creation on Linux)
        cp temp-binaries/aws-assume-role-macos-x86_64 releases/multi-shell/aws-assume-role-macos
        cp temp-binaries/aws-assume-role-linux-x86_64 releases/multi-shell/aws-assume-role-unix
        cp temp-binaries/aws-assume-role.exe releases/multi-shell/
        
        # Make binaries executable
        chmod +x releases/multi-shell/aws-assume-role-*
    
    - name: Create distribution packages
      run: |
        cd releases/multi-shell
        ./create-distribution.sh
    
    - name: Upload distribution packages
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: releases/multi-shell/dist/aws-assume-role-cli-*
        file_glob: true
        tag: ${{ github.ref }}
        overwrite: true

  publish-container:
    name: Build and publish Docker container
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Download Linux binary
      run: |
        curl -L -o aws-assume-role-linux-x86_64 \
          "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/aws-assume-role-linux-x86_64"
        mkdir -p target/release/
        mv aws-assume-role-linux-x86_64 target/release/aws-assume-role
        chmod +x target/release/aws-assume-role
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=ref,event=tag
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=raw,value=latest,enable={{is_default_branch}}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max 